apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hex
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: design.bitnami.com
    http:
      paths:
      - backend:
          serviceName: hex
          servicePort: 80
        path: "/"
  tls:
  - hosts:
    # auto-certs only support a single host per Ingress
    - design.bitnami.com
    secretName: hex-cert
